version: "3.9"
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: "user-service"
    depends_on: 
      - user-db
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - WWWPORT:3000
      - MONGODB_URL:mongodb://user-db:27017
  user-db:
    image: mongo:latest
    container_name: "user-db"
    command: mongod --port 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=user
      - MONGODB_PASS=pass
    volumes:
      - ./data/user-db:/data/db
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  url-service:
    build:
      context: ./url-service
      dockerfile: Dockerfile
    container_name: "url-service"
    depends_on: 
      - url-db
    ports:
      - 5000:5000
      - 9339:9339
    environment:
      - WWWPORT:5000
      - MONGODB_URL:mongodb://url-db:27018
  url-db:
    image: mongo:latest
    command: mongod --port 27018
    container_name: "url-db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER=user
      - MONGODB_PASS=pass
    volumes:
      - ./data/url-db:/data/db
    ports:
        - 27018:27018
    command: mongod --logpath=/dev/null # --quiet